version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55word"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  
  api:
    build: .
    ports:
      - "49153:443"
      - "49154:80"
    
